name: Workflow for Codecov example-java-maven
on: [push, pull_request]
jobs:
  check:
    name: Check and lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Check code style
        run: mvn spotless:check

  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests and collect coverage
        run: mvn -B test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  required:
    name: Required
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ check, run ]
    steps:
      - name: Guardian
        run: |
          if [[ ! ( \
                 "${{ needs.run.result }}" == "success" \
              && "${{ needs.check.result }}" == "success" \
              ) ]]; then
            echo "Required jobs haven't been completed successfully."
            exit -1
          fi      
